FROM node:18-alpine

WORKDIR /app

# Clone medusa backend
RUN npm install -g @medusajs/medusa-cli

RUN medusa new my-medusa-app --starter --no-git && \
    cd my-medusa-app && \
    npm install

WORKDIR /app/my-medusa-app

EXPOSE 9000

CMD ["npm", "run", "start"]